### ISSUE TITLE
Featured Problem Set link is wrong

### ISSUE THREAD

**Issue by myName2243** [howlbits/codescrim#11]
**This is a(n):**

- [ ] Error				
- [X] Bug				
- [ ] Feature proposal	

**Behavior:**

The featured problem set is currently HP CodeWars 2018 but clicking the "VIEW PROBLEM SET" link below it links to Codecember 2017

**Details:**

![image](https://user-images.githubusercontent.com/23108710/38578917-f440246a-3cca-11e8-8320-b22ab762b208.png)

![image](https://user-images.githubusercontent.com/23108710/38578930-fce2244c-3cca-11e8-86f5-6d3bffeaf028.png)

**Comment by geooot** [comment]
Fixed
