### ISSUE TITLE
Newly created problems cannot be viewed

### ISSUE THREAD

**Issue by GrandPanda** [howlbits/codescrim#2]
**This is a(n):**
- [ ] Error
- [X] Bug	
- [ ] Feature proposal

**Behavior:**
Newly created problems cannot be viewed in the problem set until webpage is refreshed.

**Details:**
1. Create a problem set
2. Add a problem
3. After being redirected to the Your Problem Sets page, click on the problem set the problem was added to.
4. The menu doesn't list the problem that was just created.

**Comment by myName2243** [comment]
This also includes editing a problem from the problem view, saving it, and then when the website brings you back to the problem view, it shows you the outdated version of the problem.

**Comment by geooot** [comment]
Yes this is a caching issue, will fix

**Comment by geooot** [comment]
I have just put out a build that addresses this issue.
