### ISSUE TITLE
Logging out in the admin view doesn't work

### ISSUE THREAD

**Issue by myName2243** [howlbits/codescrim#3]
**This is a(n):**

- [ ] Error				
- [x] Bug				
- [ ] Feature proposal	

**Behavior:**

If I'm, say, currently viewing the list of problem sets in the manage menu, and decide to click "Log out" from that page, instead of getting logged out of my account so I can sign into, say, my non-admin account, it puts me on the team dashboard still logged in.

Perhaps it should log me out? That's what I would expect :/

**Comment by geooot** [comment]
This is a known error. I don't know why it doesn't log out from the admin view, as the same code works on any other page. Working on it

**Comment by geooot** [comment]
Fixed in the latest release of the website
