### ISSUE TITLE
Reordering problems in a set

### ISSUE THREAD

**Issue by matthew-zhang-306** [howlbits/codescrim#4]
**This is a(n):**

- [ ] Error				
- [ ] Bug				
- [X] Feature proposal	

**Details:**

I put the District UIL problems in from easiest-to-create to hardest-to-create. Can I reorder them so that they go alphabetically instead?

**Comment by geooot** [comment]
This feature is planned. I am thinking of allowing for sorting by Alphabet and by point value only.

**Comment by geooot** [comment]
Added ability to sort problems in admin view
![kapture 2018-09-11 at 13 17 35](https://user-images.githubusercontent.com/7832610/45379254-29d7e680-b5c5-11e8-8a5d-4f3d55edd962.gif)
