### ISSUE TITLE
The "Solve Problem Online" button is weird

### ISSUE THREAD

**Issue by myName2243** [howlbits/codescrim#6]
**This is a(n):**

- [ ] Error				
- [X] Bug				
- [ ] Feature proposal	

**Behavior:**

A small bug you probably know about already. If I press the green "Solve Problem Online" button on the green part on the side and not directly on the text, it does nothing. It only works when I click the text "Solve Problem Online". Seems kinda odd, doesn't it>

**Comment by geooot** [comment]
Fixed 👍
