### ISSUE TITLE
Changing the flair color of a problem set

### ISSUE THREAD

**Issue by myName2243** [howlbits/codescrim#7]
**This is a(n):**

- [ ] Error				
- [ ] Bug				
- [X] Feature proposal	

**Behavior:**

If I have a problem set that's red but then I realize I want it orange instead because this other problem set idea I had would be better with the color red, I should be able to change it from red to orange.

**Details:**

In the "Edit Set" dialogue, There should be a color swatch or something on the side that I can click to change. I could set it to any color I want on the color wheel.

**Comment by geooot** [comment]
Done did it. The build will be up soon enough
